version: '3'
services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx     
    ports:
      - "5080:8080"
    volumes:
      - ./html:/usr/share/nginx/html
    depends_on:
      - php

  php:
    build:
      context: .
      dockerfile: Dockerfile.php
    volumes:
      - ./html:/usr/share/nginx/html
