FROM nginx:mainline-alpine

LABEL maintainer="s2w"

RUN apk update
RUN apk upgrade
RUN rm /etc/nginx/conf.d/default.conf

COPY ./config/nginx.conf /etc/nginx/conf.d/app.conf

COPY html/ /var/www/html

EXPOSE 8080

CMD ["nginx", "-g", "daemon off;"]
