FROM nginx:latest

LABEL maintainer="s2w"

RUN apt-get update -y
RUN apt-get upgrade -y
RUN rm /etc/nginx/conf.d/default.conf

COPY ./config/nginx.conf /etc/nginx/conf.d/app.conf

COPY html/ /usr/share/nginx/html/

EXPOSE 8080

CMD ["nginx", "-g", "daemon off;"]
